# For documentation, see https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - gofumpt
    - errorlint
    - unconvert
    - unparam

linters-settings:
  govet:
    enable:
      - nilness
